# Generated by Django 4.2.16 on 2026-06-24 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_hash', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('gender', models.CharField(blank=True, max_length=8)),
                ('household_province', models.CharField(blank=True, help_text='户口所在地', max_length=32)),
                ('first_degree_school', models.CharField(blank=True, max_length=128)),
                ('highest_degree_school', models.CharField(blank=True, max_length=128)),
                ('highest_major', models.CharField(blank=True, max_length=128)),
                ('first_degree_platform', models.CharField(blank=True, max_length=64)),
                ('highest_degree_platform', models.CharField(blank=True, max_length=64)),
                ('is_target_school', models.BooleanField(default=False)),
                ('imported_at', models.DateTimeField(auto_now_add=True, help_text='导入时间（时间标签）')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('level', models.PositiveSmallIntegerField(default=2, help_text='1=一层, 2=二层')),
                ('entity', models.CharField(blank=True, help_text='招聘主体', max_length=64)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.department')),
            ],
            options={
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(blank=True, help_text='主体', max_length=64)),
                ('category', models.CharField(blank=True, help_text='岗位类别', max_length=64)),
                ('public_name', models.CharField(blank=True, help_text='对外发布名称', max_length=128)),
                ('is_public', models.BooleanField(default=True, help_text='是否对外发布')),
                ('position_name', models.CharField(blank=True, help_text='职位名称', max_length=128)),
                ('job_family', models.CharField(blank=True, help_text='岗位族', max_length=64)),
                ('location', models.CharField(blank=True, help_text='工作地点', max_length=64)),
                ('education', models.CharField(blank=True, help_text='学历要求', max_length=32)),
                ('headcount', models.PositiveIntegerField(default=0, help_text='需求数量(HC)')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.JSONField(blank=True, default=dict, help_text='处理范围/筛选条件')),
                ('step', models.CharField(max_length=16)),
                ('mode', models.CharField(default='rule', max_length=8)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('celery_task_id', models.CharField(blank=True, max_length=64)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProvinceRegion',
            fields=[
                ('province', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('region', models.CharField(help_text='南/北', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='学校', max_length=128, unique=True)),
                ('platform', models.CharField(blank=True, help_text='平台标签', max_length=64)),
                ('region', models.CharField(blank=True, help_text='南/北（户籍缺失兜底）', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_id', models.CharField(help_text='应聘ID', max_length=64, unique=True)),
                ('resume_file', models.CharField(blank=True, help_text='简历包文件名', max_length=256)),
                ('entity', models.CharField(blank=True, help_text='招聘主体', max_length=64)),
                ('org', models.CharField(blank=True, help_text='所属机构', max_length=128)),
                ('position_name', models.CharField(blank=True, help_text='对外职位名称', max_length=128)),
                ('status', models.CharField(blank=True, default='待处理', help_text='应聘状态', max_length=32)),
                ('apply_date', models.DateField(blank=True, help_text='应聘日期', null=True)),
                ('volunteer_rank', models.PositiveSmallIntegerField(blank=True, help_text='志愿次序 1-4', null=True)),
                ('assigned_entity', models.CharField(blank=True, help_text='分配主体 GW/YLS', max_length=16)),
                ('job_category', models.CharField(blank=True, help_text='岗位类别标签', max_length=64)),
                ('category_mode', models.CharField(blank=True, help_text='rule/ai', max_length=8)),
                ('category_reason', models.TextField(blank=True, help_text='AI 模式可解释理由')),
                ('imported_at', models.DateTimeField(auto_now_add=True, help_text='导入时间（时间标签）')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='core.candidate')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='core.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=64)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='core.job')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('employee_no', models.CharField(help_text='工号', max_length=32, unique=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, help_text='分配理由', max_length=64)),
                ('match_mode', models.CharField(blank=True, help_text='rule/ai', max_length=8)),
                ('status', models.CharField(default='待下发', max_length=16)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contact')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.resume')),
            ],
        ),
    ]
