# Generated by Django 4.2.16 on 2026-06-30 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('auto', '自动分配'), ('manual', '手动强制分配')], default='auto', max_length=16)),
                ('status', models.CharField(choices=[('pending_dispatch', '待下发'), ('dispatched', '已下发'), ('passed', '已通过'), ('rejected', '未通过'), ('cancelled', '已取消')], default='pending_dispatch', max_length=32)),
                ('match_mode', models.CharField(blank=True, help_text='rule/ai', max_length=8)),
                ('match_reason', models.TextField(blank=True)),
                ('welink_message_id', models.CharField(blank=True, max_length=128)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('feedback_result', models.CharField(blank=True, choices=[('passed', '通过'), ('rejected', '未通过')], max_length=16)),
                ('feedback_note', models.TextField(blank=True)),
                ('feedback_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=64)),
                ('manual_reason', models.TextField(blank=True)),
                ('department_name_snapshot', models.CharField(blank=True, max_length=128)),
                ('contact_name_snapshot', models.CharField(blank=True, max_length=64)),
                ('contact_employee_no_snapshot', models.CharField(blank=True, max_length=32)),
                ('resume_apply_id_snapshot', models.CharField(blank=True, max_length=64)),
                ('position_name_snapshot', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_hash', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('gender', models.CharField(blank=True, max_length=8)),
                ('household_province', models.CharField(blank=True, help_text='户口所在地', max_length=32)),
                ('first_degree_school', models.CharField(blank=True, max_length=128)),
                ('highest_degree_school', models.CharField(blank=True, max_length=128)),
                ('highest_major', models.CharField(blank=True, max_length=128)),
                ('first_degree_platform', models.CharField(blank=True, max_length=64)),
                ('highest_degree_platform', models.CharField(blank=True, max_length=64)),
                ('imported_at', models.DateTimeField(auto_now_add=True, help_text='导入时间（时间标签）')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('level', models.PositiveSmallIntegerField(default=2, help_text='1=一层, 2=二层')),
                ('entity', models.CharField(blank=True, help_text='招聘主体', max_length=64)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.department')),
            ],
            options={
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='ImportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('payload', models.TextField(help_text='django serialize 的 json')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(blank=True, help_text='主体', max_length=64)),
                ('category', models.CharField(blank=True, help_text='岗位类别', max_length=64)),
                ('public_name', models.CharField(blank=True, help_text='对外发布名称', max_length=128)),
                ('is_public', models.BooleanField(default=True, help_text='是否对外发布')),
                ('position_name', models.CharField(blank=True, help_text='职位名称', max_length=128)),
                ('job_family', models.CharField(blank=True, help_text='岗位族', max_length=64)),
                ('location', models.CharField(blank=True, help_text='工作地点', max_length=64)),
                ('education', models.CharField(blank=True, help_text='学历要求', max_length=32)),
                ('headcount', models.PositiveIntegerField(default=0, help_text='需求数量(HC)')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.JSONField(blank=True, default=dict, help_text='处理范围/筛选条件')),
                ('step', models.CharField(max_length=16)),
                ('mode', models.CharField(default='rule', max_length=8)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('celery_task_id', models.CharField(blank=True, max_length=64)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProvinceRegion',
            fields=[
                ('province', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('region', models.CharField(help_text='南/北', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='学校', max_length=128, unique=True)),
                ('platform', models.CharField(blank=True, help_text='平台标签', max_length=64)),
                ('region', models.CharField(blank=True, help_text='南/北（户籍缺失兜底）', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolTagRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('first_degree_tags', models.JSONField(blank=True, default=list)),
                ('highest_degree_tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'id'],
                'indexes': [models.Index(fields=['is_active', 'priority'], name='core_school_is_acti_ffb658_idx')],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_id', models.CharField(help_text='应聘ID', max_length=64, unique=True)),
                ('resume_file', models.CharField(blank=True, help_text='简历包文件名', max_length=256)),
                ('entity', models.CharField(blank=True, help_text='招聘主体', max_length=64)),
                ('org', models.CharField(blank=True, help_text='所属机构', max_length=128)),
                ('position_name', models.CharField(blank=True, help_text='对外职位名称', max_length=128)),
                ('status', models.CharField(blank=True, default='待处理', help_text='应聘状态', max_length=32)),
                ('apply_date', models.DateField(blank=True, help_text='应聘日期', null=True)),
                ('volunteer_rank', models.PositiveSmallIntegerField(blank=True, help_text='志愿次序 1-4', null=True)),
                ('assigned_entity', models.CharField(blank=True, help_text='分配主体 GW/YLS', max_length=16)),
                ('job_category', models.CharField(blank=True, help_text='岗位类别标签', max_length=64)),
                ('category_mode', models.CharField(blank=True, help_text='rule/ai', max_length=8)),
                ('category_reason', models.TextField(blank=True, help_text='AI 模式可解释理由')),
                ('imported_at', models.DateTimeField(auto_now_add=True, help_text='导入时间（时间标签）')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='core.candidate')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='core.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=64)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='core.job')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('employee_no', models.CharField(help_text='工号', max_length=32, unique=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待分配'), ('in_progress', '进行中'), ('passed', '已通过'), ('archived', '已归档')], default='pending', max_length=32)),
                ('current_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('archive_reason', models.CharField(blank=True, choices=[('no_active_school_rule', '没有启用院校标签准入规则'), ('school_rule_not_matched', '院校标签未命中规则'), ('no_next_resume', '没有下一条可尝试志愿'), ('job_not_matched', '未匹配岗位'), ('department_not_found', '无有效二层部门'), ('contact_not_found', '无可用接口人'), ('all_rejected', '全部志愿未通过'), ('rerun_preserved', '重跑时保留归档')], max_length=64)),
                ('archive_detail', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='core.candidate')),
                ('current_resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_workflows', to='core.resume')),
                ('passed_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passed_workflows', to='core.assignmentattempt')),
            ],
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_attempts', to='core.contact'),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_attempts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_attempts', to='core.department'),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='matched_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_attempts', to='core.schooltagrule'),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_attempts', to='core.resume'),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.candidateworkflow'),
        ),
        migrations.AddIndex(
            model_name='candidateworkflow',
            index=models.Index(fields=['status'], name='core_candid_status_58f14e_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateworkflow',
            index=models.Index(fields=['updated_at'], name='core_candid_updated_b74906_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentattempt',
            index=models.Index(fields=['status'], name='core_assign_status_206ab2_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentattempt',
            index=models.Index(fields=['contact', 'status'], name='core_assign_contact_347b59_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentattempt',
            index=models.Index(fields=['workflow', 'status'], name='core_assign_workflo_6893ef_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentattempt',
            index=models.Index(fields=['source', 'status'], name='core_assign_source_97fd75_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentattempt',
            unique_together={('workflow', 'attempt_no')},
        ),
    ]
