# Generated by Django 4.2.16 on 2026-06-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('payload', models.TextField(help_text='django serialize 的 json')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
