# Generated by Django 4.2.16 on 2026-06-30 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDispatchDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(choices=[('dispatch', '建议下发'), ('review', '人工复核'), ('archive', '建议归档')], max_length=16)),
                ('confidence_score', models.FloatField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('risks', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('prompt_version', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('hr_dispatch', 'HR 下发二级'), ('sub_assign', '二级转派三级'), ('sub_reassign', '二级改派三级')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parsed_text', models.TextField(blank=True)),
                ('projects', models.JSONField(blank=True, default=list)),
                ('internships', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('certificates', models.JSONField(blank=True, default=list)),
                ('major_direction', models.CharField(blank=True, max_length=128)),
                ('parse_status', models.CharField(default='pending', max_length=32)),
                ('parse_error', models.TextField(blank=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='assigned_to_sub_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='review_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='sub_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_assignment_attempts', to='core.contact'),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='sub_contact_employee_no_snapshot',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='sub_contact_name_snapshot',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='sub_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_assignment_attempts', to='core.department'),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='sub_department_name_snapshot',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='candidateworkflow',
            name='dispatch_strategy',
            field=models.CharField(default='rule', max_length=16),
        ),
        migrations.AddField(
            model_name='contact',
            name='can_delegate',
            field=models.BooleanField(default=True, help_text='二级接口人是否可转派'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_level',
            field=models.CharField(choices=[('secondary', '二级接口人'), ('tertiary', '三级接口人')], default='secondary', max_length=16),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='assignmentattempt',
            name='source',
            field=models.CharField(choices=[('rule', '规则分配'), ('ai', 'AI 分配'), ('manual', '手动强制分配')], default='rule', max_length=16),
        ),
        migrations.AlterField(
            model_name='assignmentattempt',
            name='status',
            field=models.CharField(choices=[('pending_dispatch', '待下发'), ('dispatched_l2', '已下发二级'), ('assigned_l3', '已转派三级'), ('passed', '已通过'), ('rejected', '未通过'), ('cancelled', '已取消')], default='pending_dispatch', max_length=32),
        ),
        migrations.AlterField(
            model_name='candidateworkflow',
            name='archive_reason',
            field=models.CharField(blank=True, choices=[('no_active_school_rule', '没有启用院校标签准入规则'), ('school_rule_not_matched', '院校标签未命中规则'), ('no_next_resume', '没有下一条可尝试志愿'), ('job_not_matched', '未匹配岗位'), ('department_not_found', '无有效二层部门'), ('contact_not_found', '无可用接口人'), ('sub_contact_not_found', '二级部门下没有可用三级接口人'), ('agent_no_recommendation', 'AI 无有效建议'), ('all_rejected', '全部志愿未通过'), ('rerun_preserved', '重跑时保留归档')], max_length=64),
        ),
        migrations.AlterField(
            model_name='department',
            name='level',
            field=models.PositiveSmallIntegerField(default=2, help_text='1=一层, 2=二层, 3=三级'),
        ),
        migrations.AddIndex(
            model_name='assignmentattempt',
            index=models.Index(fields=['sub_contact', 'status'], name='core_assign_sub_con_a573ed_idx'),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.resume'),
        ),
        migrations.AddField(
            model_name='assignmenthandoff',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoffs', to='core.assignmentattempt'),
        ),
        migrations.AddField(
            model_name='assignmenthandoff',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_handoffs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmenthandoff',
            name='from_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoffs_from', to='core.contact'),
        ),
        migrations.AddField(
            model_name='assignmenthandoff',
            name='to_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handoffs_to', to='core.contact'),
        ),
        migrations.AddField(
            model_name='assignmenthandoff',
            name='to_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoffs_to', to='core.department'),
        ),
        migrations.AddField(
            model_name='agentdispatchdecision',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_decisions', to='core.resumeprofile'),
        ),
        migrations.AddField(
            model_name='agentdispatchdecision',
            name='recommended_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_decisions', to='core.contact'),
        ),
        migrations.AddField(
            model_name='agentdispatchdecision',
            name='recommended_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_decisions', to='core.department'),
        ),
        migrations.AddField(
            model_name='agentdispatchdecision',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_decisions', to='core.resume'),
        ),
        migrations.AddField(
            model_name='agentdispatchdecision',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_decisions', to='core.candidateworkflow'),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='agent_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_attempts', to='core.agentdispatchdecision'),
        ),
        migrations.AddIndex(
            model_name='assignmenthandoff',
            index=models.Index(fields=['attempt', 'created_at'], name='core_assign_attempt_ada387_idx'),
        ),
        migrations.AddIndex(
            model_name='agentdispatchdecision',
            index=models.Index(fields=['workflow', 'created_at'], name='core_agentd_workflo_04926e_idx'),
        ),
        migrations.AddIndex(
            model_name='agentdispatchdecision',
            index=models.Index(fields=['recommendation', 'confidence_score'], name='core_agentd_recomme_06de68_idx'),
        ),
    ]
