# Generated by Codex on 2026-06-30

from django.db import migrations


def normalize_assignment_attempts(apps, schema_editor):
    AssignmentAttempt = apps.get_model("core", "AssignmentAttempt")
    AssignmentAttempt.objects.filter(source="auto").update(source="rule")
    AssignmentAttempt.objects.filter(status="dispatched").update(status="dispatched_l2")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_agentdispatchdecision_assignmenthandoff_and_more"),
    ]

    operations = [
        migrations.RunPython(normalize_assignment_attempts, migrations.RunPython.noop),
    ]
