# Generated by Codex on 2026-06-30

from django.db import migrations


def seed_demo_school_tag_rule(apps, schema_editor):
    SchoolTagRule = apps.get_model("core", "SchoolTagRule")
    if SchoolTagRule.objects.exists():
        return
    SchoolTagRule.objects.create(
        name="Demo 默认目标院校",
        first_degree_tags=["平台A", "平台B", "平台C"],
        highest_degree_tags=["平台A", "平台B", "平台C"],
        is_active=True,
        priority=0,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_normalize_workflow_values"),
    ]

    operations = [
        migrations.RunPython(seed_demo_school_tag_rule, migrations.RunPython.noop),
    ]
