# Generated by Django 4.2.16 on 2026-07-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_demo_school_tag_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentattempt',
            name='status',
            field=models.CharField(choices=[('pending_dispatch', '待下发'), ('pending_review', '待 HR 复核'), ('dispatched_l2', '已下发二级'), ('assigned_l3', '已转派三级'), ('passed', '已通过'), ('rejected', '未通过'), ('cancelled', '已取消')], default='pending_dispatch', max_length=32),
        ),
    ]
