# Generated by Django 4.2.16 on 2026-07-02 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_assignmentattempt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdispatchdecision',
            name='decision_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='agentdispatchdecision',
            name='error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='agentdispatchdecision',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentdispatchdecision',
            name='evaluated_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_evaluations', to='core.job'),
        ),
        migrations.AddField(
            model_name='agentdispatchdecision',
            name='matched_job_category',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='agentdispatchdecision',
            name='processing_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_decisions', to='core.processingrun'),
        ),
        migrations.AddField(
            model_name='agentdispatchdecision',
            name='recommended_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_recommendations', to='core.job'),
        ),
        migrations.AddField(
            model_name='agentdispatchdecision',
            name='risk_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agentdispatchdecision',
            name='score_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agentdispatchdecision',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='agentdispatchdecision',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentdispatchdecision',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('dispatch', '建议下发'), ('review', '人工复核'), ('archive', '建议归档')], max_length=16, null=True),
        ),
    ]
