# Generated by Django 4.2.16 on 2026-07-08 02:02

from django.db import migrations, models
import django.db.models.deletion


def migrate_school_tags_and_rules(apps, schema_editor):
    Candidate = apps.get_model("core", "Candidate")
    School = apps.get_model("core", "School")
    SchoolTag = apps.get_model("core", "SchoolTag")
    SchoolTagRule = apps.get_model("core", "SchoolTagRule")
    SchoolTagRuleTag = apps.get_model("core", "SchoolTagRuleTag")

    tag_cache = {}

    def tag_for(value):
        text = str(value or "").strip()
        if not text:
            return None
        if text not in tag_cache:
            tag_cache[text], _ = SchoolTag.objects.get_or_create(
                code=text,
                defaults={
                    "name": text,
                    "is_default": text == "非目标院校",
                    "is_active": True,
                },
            )
        return tag_cache[text]

    for school in School.objects.exclude(platform=""):
        school_tag = tag_for(school.platform)
        if school_tag:
            school.school_tag_id = school_tag.id
            school.save(update_fields=["school_tag"])

    for candidate in Candidate.objects.all():
        update_fields = []
        first_tag = tag_for(candidate.first_degree_platform)
        highest_tag = tag_for(candidate.highest_degree_platform)
        if first_tag:
            candidate.first_degree_tag_id = first_tag.id
            update_fields.append("first_degree_tag")
        if highest_tag:
            candidate.highest_degree_tag_id = highest_tag.id
            update_fields.append("highest_degree_tag")
        if update_fields:
            candidate.save(update_fields=update_fields)

    for rule in SchoolTagRule.objects.all():
        for value in rule.first_degree_tags or []:
            school_tag = tag_for(value)
            if school_tag:
                SchoolTagRuleTag.objects.get_or_create(
                    rule_id=rule.id,
                    school_tag_id=school_tag.id,
                    degree_type="first",
                )
        for value in rule.highest_degree_tags or []:
            school_tag = tag_for(value)
            if school_tag:
                SchoolTagRuleTag.objects.get_or_create(
                    rule_id=rule.id,
                    school_tag_id=school_tag.id,
                    degree_type="highest",
                )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_agentdispatchdecision_decision_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code', 'id'],
            },
        ),
        migrations.AddField(
            model_name='school',
            name='province',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name='SchoolTagRuleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_type', models.CharField(choices=[('first', '第一学历'), ('highest', '最高学历')], max_length=16)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='core.schooltagrule')),
                ('school_tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_links', to='core.schooltag')),
            ],
        ),
        migrations.AddIndex(
            model_name='schooltag',
            index=models.Index(fields=['code', 'is_active'], name='core_school_code_f8c5cc_idx'),
        ),
        migrations.AddIndex(
            model_name='schooltag',
            index=models.Index(fields=['is_default'], name='core_school_is_defa_a82edf_idx'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='first_degree_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_degree_candidates', to='core.schooltag'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='highest_degree_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highest_degree_candidates', to='core.schooltag'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='core.schooltag'),
        ),
        migrations.RunPython(
            migrate_school_tags_and_rules,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='schooltagruletag',
            index=models.Index(fields=['rule', 'degree_type'], name='core_school_rule_id_db4274_idx'),
        ),
        migrations.AddIndex(
            model_name='schooltagruletag',
            index=models.Index(fields=['school_tag', 'degree_type'], name='core_school_school__464ca9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schooltagruletag',
            unique_together={('rule', 'school_tag', 'degree_type')},
        ),
        migrations.RemoveField(
            model_name='schooltagrule',
            name='first_degree_tags',
        ),
        migrations.RemoveField(
            model_name='schooltagrule',
            name='highest_degree_tags',
        ),
    ]
