# Generated by Django 4.2.16 on 2026-07-08 04:11

from django.db import migrations, models


def populate_candidate_pinyin(apps, schema_editor):
    Candidate = apps.get_model("core", "Candidate")
    try:
        from pypinyin import Style, lazy_pinyin
    except ImportError:
        Style = None
        lazy_pinyin = None

    fallback = {
        "张": "zhang",
        "三": "san",
        "李": "li",
        "四": "si",
        "王": "wang",
        "五": "wu",
        "赵": "zhao",
        "六": "liu",
    }

    def clean(value):
        return "".join(ch for ch in value.lower() if ch.isalnum())

    for candidate in Candidate.objects.all().iterator():
        if lazy_pinyin:
            syllables = lazy_pinyin(candidate.name, style=Style.NORMAL, errors="ignore")
        else:
            syllables = [fallback[ch] for ch in candidate.name if ch in fallback]
        candidate.name_pinyin = clean("".join(syllables))
        candidate.name_pinyin_initials = clean(
            "".join(item[0] for item in syllables if item)
        )
        candidate.save(update_fields=["name_pinyin", "name_pinyin_initials"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_schooltag_school_province_schooltagruletag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='name_pinyin',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='candidate',
            name='name_pinyin_initials',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(
            populate_candidate_pinyin,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['name'], name='core_candid_name_446b01_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['name_pinyin'], name='core_candid_name_pi_f1e254_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['name_pinyin_initials'], name='core_candid_name_pi_2e2e66_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active', 'entity'], name='core_job_is_acti_f59d8e_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active', 'category'], name='core_job_is_acti_6b8af2_idx'),
        ),
    ]
