# Generated by Django 4.2.16 on 2026-07-08 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_candidate_name_pinyin_candidate_name_pinyin_initials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentattempt',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_attempts', to='core.contact'),
        ),
        migrations.AlterField(
            model_name='assignmentattempt',
            name='sub_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_assignment_attempts', to='core.contact'),
        ),
        migrations.AlterField(
            model_name='assignmenthandoff',
            name='to_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoffs_to', to='core.contact'),
        ),
    ]
