# Generated by Django 4.2.16 on 2026-07-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_assignmentattempt_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdispatchdecision',
            name='recommended_contact_employee_no_snapshot',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='agentdispatchdecision',
            name='recommended_contact_name_snapshot',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='created_by_username_snapshot',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='assignmenthandoff',
            name='created_by_username_snapshot',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='assignmenthandoff',
            name='from_contact_employee_no_snapshot',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='assignmenthandoff',
            name='from_contact_name_snapshot',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='assignmenthandoff',
            name='to_contact_employee_no_snapshot',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='assignmenthandoff',
            name='to_contact_name_snapshot',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='assignmenthandoff',
            name='to_department_name_snapshot',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
