# Generated by Django 4.2.16 on 2026-07-09 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_agentdispatchdecision_recommended_contact_employee_no_snapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'code', 'id'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='core_majorc_is_acti_65a7e3_idx'), models.Index(fields=['code', 'is_active'], name='core_majorc_code_cbcec4_idx')],
            },
        ),
        migrations.CreateModel(
            name='MajorAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('normalized_name', models.CharField(max_length=128)),
                ('match_type', models.CharField(choices=[('exact', '精确匹配'), ('contains', '包含匹配')], default='contains', max_length=16)),
                ('source', models.CharField(choices=[('builtin', '内置'), ('user', '人工维护'), ('import', '导入')], default='user', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='core.majorcategory')),
            ],
            options={
                'ordering': ['category__sort_order', 'category__code', 'name', 'id'],
                'indexes': [models.Index(fields=['normalized_name', 'is_active'], name='core_majora_normali_2bdabd_idx'), models.Index(fields=['match_type', 'is_active'], name='core_majora_match_t_aa66f6_idx'), models.Index(fields=['source'], name='core_majora_source_3dad91_idx')],
            },
        ),
    ]
