# Generated by Django 4.2.16 on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_majorcategory_majoralias"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateworkflow",
            name="block_detail",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="candidateworkflow",
            name="block_reason",
            field=models.CharField(
                blank=True,
                choices=[("contact_not_found", "当前志愿无可用二级接口人")],
                max_length=64,
            ),
        ),
    ]
