# Generated by Django 4.2.16 on 2026-07-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_candidateworkflow_block_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeprofile',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='file_checksum',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='parser_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='profile_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='risk_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
