# Generated by Django 4.2.16 on 2026-07-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_resumeprofile_education_resumeprofile_file_checksum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingrun',
            name='failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingrun',
            name='processed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingrun',
            name='success_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingrun',
            name='total_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
