# Generated by Django 4.2.16 on 2026-07-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_align_ai_profile_and_processing_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateworkflow',
            name='archive_reason',
            field=models.CharField(blank=True, choices=[('no_active_school_rule', '没有启用院校标签准入规则'), ('school_rule_not_matched', '院校标签未命中规则'), ('no_next_resume', '没有下一条可尝试志愿'), ('job_not_matched', '未匹配岗位'), ('department_not_found', '无有效二层部门'), ('contact_not_found', '无可用接口人'), ('sub_contact_not_found', '二级部门下没有可用三级接口人'), ('agent_no_recommendation', 'AI 无有效建议'), ('hr_cancelled', 'HR 取消当前分配'), ('all_rejected', '全部志愿未通过'), ('rerun_preserved', '重跑时保留归档')], max_length=64),
        ),
    ]
