# Generated by Django 4.2.16 on 2026-07-10 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_alter_candidateworkflow_archive_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingRunScopeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingRunStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('step', models.CharField(max_length=16)),
                ('label', models.CharField(max_length=64)),
                ('status', models.CharField(default='pending', max_length=24)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('dispatch_count', models.PositiveIntegerField(default=0)),
                ('archive_count', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.AddField(
            model_name='processingrun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_runs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processingrun',
            name='created_by_username_snapshot',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='processingrun',
            name='current_stage',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='processingrun',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingrun',
            name='scope_summary',
            field=models.JSONField(blank=True, default=dict, help_text='可对外展示的处理范围摘要'),
        ),
        migrations.AlterField(
            model_name='processingrun',
            name='status',
            field=models.CharField(default='pending', max_length=24),
        ),
        migrations.AddIndex(
            model_name='processingrun',
            index=models.Index(fields=['status', 'created_at'], name='core_proces_status_e4ace1_idx'),
        ),
        migrations.AddIndex(
            model_name='processingrun',
            index=models.Index(fields=['created_by', 'status'], name='core_proces_created_973531_idx'),
        ),
        migrations.AddField(
            model_name='processingrunstage',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.processingrun'),
        ),
        migrations.AddField(
            model_name='processingrunscopeitem',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_scope_items', to='core.candidate'),
        ),
        migrations.AddField(
            model_name='processingrunscopeitem',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_items', to='core.processingrun'),
        ),
        migrations.AddIndex(
            model_name='processingrunstage',
            index=models.Index(fields=['run', 'status'], name='core_proces_run_id_be8140_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='processingrunstage',
            unique_together={('run', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='processingrunscopeitem',
            index=models.Index(fields=['run', 'candidate'], name='core_proces_run_id_256ef3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='processingrunscopeitem',
            unique_together={('run', 'candidate')},
        ),
    ]
