# Generated by Django 4.2.16 on 2026-07-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_processingrunscopeitem_processingrunstage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateworkflow',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingrunscopeitem',
            name='skip_reason',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='processingrunscopeitem',
            name='status',
            field=models.CharField(default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='processingrunscopeitem',
            name='workflow_revision_at_submit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
