# Generated by Django 4.2.16 on 2026-07-13 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_candidateworkflow_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingrun',
            name='cancel_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingrun',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingrun',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_runs_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processingrun',
            name='cancelled_by_username_snapshot',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
