# Generated by Django 4.2.16 on 2026-07-13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_processingrun_cancel_requested_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="school",
            name="region",
        ),
        migrations.DeleteModel(
            name="ProvinceRegion",
        ),
    ]
