# Generated by Django 4.2.16 on 2026-07-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_school_region_and_provinceregion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateworkflow',
            name='archive_reason',
            field=models.CharField(blank=True, choices=[('school_rule_not_matched', '院校标签未命中规则'), ('no_next_resume', '没有下一条可尝试志愿'), ('job_not_matched', '未匹配岗位'), ('department_not_found', '无有效二层部门'), ('agent_no_recommendation', 'AI 无有效建议'), ('hr_cancelled', 'HR 取消当前分配'), ('all_rejected', '全部志愿未通过')], max_length=64),
        ),
    ]
