# Generated by Django 4.2.16 on 2026-07-14 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_contact_school_name_pinyin'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateworkflow',
            name='active_processing_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateworkflow',
            name='active_processing_scope_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_workflow', to='core.processingrunscopeitem'),
        ),
        migrations.AddField(
            model_name='candidateworkflow',
            name='active_processing_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='processingrun',
            name='ai_concurrency_limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingrun',
            name='ai_effective_concurrency',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingrun',
            name='ai_rate_limit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingrun',
            name='ai_retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingrun',
            name='cancelled_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingrun',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingrunscopeitem',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingrunscopeitem',
            name='dispatch_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='processingrunscopeitem',
            name='error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='processingrunscopeitem',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='processingrunscopeitem',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingrunscopeitem',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingrunscopeitem',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingrunstage',
            name='cancelled_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingrunstage',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
