# Generated by Django 4.2.16 on 2026-07-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_candidateworkflow_active_processing_expires_at_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="processingrunscopeitem",
            index=models.Index(
                fields=["run", "status", "candidate"],
                name="core_scope_run_st_cand_idx",
            ),
        ),
    ]
