# Generated by Django 4.2.16 on 2026-07-15 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_processingrunscopeitem_core_scope_run_st_cand_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTagRuleEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(choices=[('associate', '大专'), ('bachelor', '本科'), ('master', '硕士'), ('doctor', '博士')], max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='highest_education',
            field=models.CharField(blank=True, choices=[('associate', '大专'), ('bachelor', '本科'), ('master', '硕士'), ('doctor', '博士')], help_text='最高学历', max_length=16),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['imported_at'], name='core_resume_importe_3c1fb9_idx'),
        ),
        migrations.AddField(
            model_name='schooltagruleeducation',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_links', to='core.schooltagrule'),
        ),
        migrations.AddIndex(
            model_name='schooltagruleeducation',
            index=models.Index(fields=['rule', 'education'], name='core_school_rule_id_37b922_idx'),
        ),
        migrations.AddConstraint(
            model_name='schooltagruleeducation',
            constraint=models.UniqueConstraint(fields=('rule', 'education'), name='core_rule_education_unique'),
        ),
    ]
