# Generated by Django 4.2.16 on 2026-07-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_schooltagruleeducation_candidate_highest_education_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='agentdispatchdecision',
            index=models.Index(fields=['created_at', 'error_code'], name='core_agentd_created_5c6de6_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentattempt',
            index=models.Index(fields=['created_at', 'source'], name='core_assign_created_0e2aa6_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentattempt',
            index=models.Index(fields=['dispatched_at'], name='core_assign_dispatc_6e1970_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentattempt',
            index=models.Index(fields=['feedback_at'], name='core_assign_feedbac_b0215d_idx'),
        ),
    ]
