# Generated by Django 4.2.16 on 2026-07-17 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_agentdispatchdecision_core_agentd_created_5c6de6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdispatchdecision',
            name='ai_specialist_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentdispatchdecision',
            name='ai_specialist_evidence',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agentdispatchdecision',
            name='ai_specialist_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentdispatchdecision',
            name='special_route_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentdispatchdecision',
            name='special_route_config_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='route_code',
            field=models.CharField(blank=True, db_index=True, help_text='特殊分流代码；普通分配为空', max_length=64),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='special_route_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='special_route_config_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='special_route_evidence',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='processingrun',
            name='completed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingrun',
            name='needs_attention_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingrunscopeitem',
            name='matched_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_processing_items', to='core.schooltagrule'),
        ),
        migrations.AddField(
            model_name='processingrunscopeitem',
            name='prepared_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_processing_items', to='core.contact'),
        ),
        migrations.AddField(
            model_name='processingrunscopeitem',
            name='prepared_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_processing_items', to='core.department'),
        ),
        migrations.AddField(
            model_name='processingrunscopeitem',
            name='prepared_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_processing_items', to='core.job'),
        ),
        migrations.AddField(
            model_name='processingrunscopeitem',
            name='prepared_resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_processing_items', to='core.resume'),
        ),
        migrations.AddField(
            model_name='processingrunscopeitem',
            name='reason_code',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='processingrunscopeitem',
            name='result_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='processingrunscopeitem',
            name='result_type',
            field=models.CharField(blank=True, choices=[('completed', '处理完成'), ('needs_attention', '需处理'), ('failed', '失败'), ('cancelled', '已取消')], max_length=32),
        ),
        migrations.AddField(
            model_name='processingrunscopeitem',
            name='workflow_revision_at_prepare',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingrunstage',
            name='completed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingrunstage',
            name='needs_attention_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='processingrunscopeitem',
            index=models.Index(fields=['run', 'result_type', 'reason_code'], name='core_scope_run_res_reason'),
        ),
    ]
