# Generated by Django 4.2.16 on 2026-07-21 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_job_responsibilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentattempt',
            name='capacity_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingrun',
            name='job_hc_coefficient_snapshot',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='candidateworkflow',
            name='archive_reason',
            field=models.CharField(blank=True, choices=[('school_rule_not_matched', '院校标签未命中规则'), ('no_next_resume', '没有下一条可尝试志愿'), ('job_not_matched', '未匹配岗位'), ('job_mapping_ambiguous', '对外职位映射到多个内部职位'), ('internal_position_name_missing', '内部职位名称缺失'), ('department_not_found', '无有效二层部门'), ('agent_no_recommendation', 'AI 无有效建议'), ('hr_cancelled', 'HR 取消当前分配'), ('all_rejected', '全部志愿未通过')], max_length=64),
        ),
        migrations.AlterField(
            model_name='candidateworkflow',
            name='block_reason',
            field=models.CharField(blank=True, choices=[('contact_not_found', '当前志愿无可用二级接口人'), ('job_hc_exhausted', '当前任务岗位 HC 容量已用尽')], max_length=64),
        ),
        migrations.CreateModel(
            name='ProcessingRunJobCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headcount_snapshot', models.PositiveIntegerField(default=0)),
                ('coefficient_snapshot', models.PositiveSmallIntegerField(default=1)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processing_capacities', to='core.job')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_capacities', to='core.processingrun')),
            ],
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='capacity_reservation',
            field=models.ForeignKey(blank=True, help_text='自动分配占用的任务级岗位容量；手工强制分配为空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='core.processingrunjobcapacity'),
        ),
        migrations.AddIndex(
            model_name='processingrunjobcapacity',
            index=models.Index(fields=['run', 'job'], name='core_proces_run_id_089910_idx'),
        ),
        migrations.AddConstraint(
            model_name='processingrunjobcapacity',
            constraint=models.UniqueConstraint(fields=('run', 'job'), name='core_run_job_capacity_unique'),
        ),
        migrations.AddConstraint(
            model_name='processingrunjobcapacity',
            constraint=models.CheckConstraint(check=models.Q(('used_count__lte', models.F('capacity'))), name='core_run_job_capacity_used_lte_capacity'),
        ),
    ]
