# Generated by Django 4.2.16 on 2026-07-22 08:38

from django.db import migrations, models


def copy_bound_user_emails(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Contact = apps.get_model("core", "Contact")
    for user in User.objects.exclude(contact_id=None).exclude(email=""):
        Contact.objects.filter(pk=user.contact_id).update(
            email=str(user.email).strip().casefold()
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_add_analytics_permission"),
        ("core", "0031_assignmentattempt_capacity_released_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.EmailField(
                blank=True, default="", help_text="公司邮箱", max_length=254
            ),
        ),
        migrations.RunPython(copy_bound_user_emails, migrations.RunPython.noop),
    ]
