# Generated by Django 4.2.16 on 2026-07-30 08:50

import hashlib
import json

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


DEFAULT_MODULES = {
    "screening_role_goal": (
        "你是校招简历深度筛选助手。请基于简历正文中的可定位证据形成结构化画像和"
        "当前岗位适配建议；证据不足或当前岗位不适合时，recommendation 必须为 archive。"
        "禁止臆造经历、技能或结论，所有分项评分均为 0 到 1。"
    ),
    "screening_rule_guardrails": (
        "学历、院校、志愿顺序、岗位存在性、岗位部门和接口人已经由后端规则确定，"
        "不得重复判断这些规则，不得选择或返回任何数据库 ID，也不得推荐其它岗位。"
        "只评估输入中的当前有效志愿和后端固定的当前岗位。"
    ),
    "screening_job_evaluation": (
        "结合简历中的专业实际方向、项目、实习和技能证据，评价岗位工作职责覆盖程度，"
        "并将结果计入 job_requirement 分项。不得因为职责文本重复判断学历、院校、岗位、"
        "部门或接口人。"
    ),
    "screening_ai_specialist": (
        "另行判断候选人是否具备实质性的智能体、大模型、RAG、微调、模型训练或推理、"
        "模型评测经历。只有简历正文存在可定位的项目、实习或技能证据时，"
        "ai_specialist_match 才能为 true，并给出独立的 ai_specialist_confidence "
        "和逐字证据片段。"
    ),
    "school_province_inference": (
        "你是中国大陆院校基础数据整理助手。请判断名称所指院校所在地的省级行政区；"
        "名称明确包含校区或分校时按该校区或分校所在地，否则按学校主校区，"
        "不得按招生地区猜测；无法可靠判断时返回空省份。"
    ),
}


def seed_prompt_versions(apps, schema_editor):
    PromptVersion = apps.get_model("core", "AIPromptVersion")
    content_hash = hashlib.sha256(
        json.dumps(
            DEFAULT_MODULES,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
        ).encode("utf-8")
    ).hexdigest()
    now = timezone.now()
    PromptVersion.objects.get_or_create(
        version="resume-screening-v2",
        defaults={
            "status": "active",
            "release_sequence": 0,
            "modules": DEFAULT_MODULES,
            "content_hash": content_hash,
            "published_at": now,
        },
    )
    PromptVersion.objects.get_or_create(
        version="draft-resume-screening-v2",
        defaults={
            "status": "draft",
            "modules": DEFAULT_MODULES,
            "content_hash": content_hash,
        },
    )


def remove_seed_prompt_versions(apps, schema_editor):
    PromptVersion = apps.get_model("core", "AIPromptVersion")
    PromptVersion.objects.filter(
        version__in=["resume-screening-v2", "draft-resume-screening-v2"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0032_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('draft', '共享草稿'), ('active', '激活'), ('archived', '已归档')], max_length=16)),
                ('release_sequence', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('modules', models.JSONField(default=dict)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('lock_version', models.PositiveIntegerField(default=0)),
                ('created_by_username_snapshot', models.CharField(blank=True, max_length=150)),
                ('updated_by_username_snapshot', models.CharField(blank=True, max_length=150)),
                ('tested_by_username_snapshot', models.CharField(blank=True, max_length=150)),
                ('tested_at', models.DateTimeField(blank=True, null=True)),
                ('test_content_hash', models.CharField(blank=True, max_length=64)),
                ('test_model_name', models.CharField(blank=True, max_length=64)),
                ('test_connection_fingerprint', models.CharField(blank=True, max_length=64)),
                ('test_summary', models.JSONField(blank=True, default=dict)),
                ('published_by_username_snapshot', models.CharField(blank=True, max_length=150)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_prompt_versions_created', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_prompt_versions_published', to=settings.AUTH_USER_MODEL)),
                ('restored_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_drafts', to='core.aipromptversion')),
                ('tested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_prompt_versions_tested', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_prompt_versions_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-release_sequence', '-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='core_aiprom_status_676bc0_idx'), models.Index(fields=['published_at'], name='core_aiprom_publish_841c38_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='aipromptversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('status',), name='core_single_ai_prompt_draft'),
        ),
        migrations.AddConstraint(
            model_name='aipromptversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('status',), name='core_single_ai_prompt_active'),
        ),
        migrations.RunPython(seed_prompt_versions, remove_seed_prompt_versions),
    ]
