# Generated by Django 4.2.16 on 2026-08-10 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0033_aipromptversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsagePageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(editable=False, unique=True)),
                ('session_id', models.UUIDField(editable=False)),
                ('employee_no_snapshot', models.CharField(max_length=150)),
                ('page_key', models.CharField(max_length=64)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_page_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['occurred_at'], name='core_usagep_occurre_11a058_idx'), models.Index(fields=['page_key', 'occurred_at'], name='core_usagep_page_ke_ea1ff0_idx'), models.Index(fields=['session_id', 'occurred_at'], name='core_usagep_session_1324c8_idx')],
            },
        ),
    ]
