# Generated by Django 4.2.16 on 2026-08-24 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def clear_incompatible_workflow_history(apps, schema_editor):
    """断代升级：保留候选人/简历/岗位/部门/接口人主数据，清空旧流程。"""

    CandidateWorkflow = apps.get_model("core", "CandidateWorkflow")
    AssignmentAttempt = apps.get_model("core", "AssignmentAttempt")
    AssignmentHandoff = apps.get_model("core", "AssignmentHandoff")
    AgentDispatchDecision = apps.get_model("core", "AgentDispatchDecision")
    ProcessingRun = apps.get_model("core", "ProcessingRun")
    ProcessingRunScopeItem = apps.get_model("core", "ProcessingRunScopeItem")
    ProcessingRunStage = apps.get_model("core", "ProcessingRunStage")
    ProcessingRunJobCapacity = apps.get_model("core", "ProcessingRunJobCapacity")
    ImportSnapshot = apps.get_model("core", "ImportSnapshot")
    Config = apps.get_model("core", "Config")

    CandidateWorkflow.objects.update(
        passed_attempt=None,
        active_processing_scope_item=None,
    )
    AssignmentAttempt.objects.update(
        agent_decision=None,
        capacity_reservation=None,
    )
    AgentDispatchDecision.objects.update(processing_run=None)
    AssignmentHandoff.objects.all().delete()
    AssignmentAttempt.objects.all().delete()
    AgentDispatchDecision.objects.all().delete()
    CandidateWorkflow.objects.all().delete()
    ProcessingRunScopeItem.objects.all().delete()
    ProcessingRunStage.objects.all().delete()
    ProcessingRunJobCapacity.objects.all().delete()
    ProcessingRun.objects.all().delete()
    ImportSnapshot.objects.all().delete()
    Config.objects.filter(
        key__in=[
            "ai_special_route_secondary_contact_id",
            "ai_special_route_tertiary_contact_id",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0034_usagepageview'),
    ]

    operations = [
        migrations.RunPython(
            clear_incompatible_workflow_history,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='AssignmentHandlingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('attempt_created', '尝试创建'), ('review_confirmed', 'HR 确认复核'), ('department_dispatched', '下发部门'), ('department_transferred', '部门转派'), ('feedback_passed', '反馈通过'), ('feedback_rejected', '反馈不通过'), ('cancelled', '取消')], max_length=32)),
                ('from_department_name_snapshot', models.CharField(blank=True, max_length=128)),
                ('to_department_name_snapshot', models.CharField(blank=True, max_length=128)),
                ('actor_username_snapshot', models.CharField(blank=True, max_length=150)),
                ('note', models.TextField(blank=True)),
                ('batch_operation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_system_auto', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
                'default_permissions': ('view',),
            },
        ),
        migrations.RemoveIndex(
            model_name='assignmentattempt',
            name='core_assign_contact_347b59_idx',
        ),
        migrations.RemoveIndex(
            model_name='assignmentattempt',
            name='core_assign_sub_con_a573ed_idx',
        ),
        migrations.RemoveField(
            model_name='agentdispatchdecision',
            name='recommended_contact',
        ),
        migrations.RemoveField(
            model_name='agentdispatchdecision',
            name='recommended_contact_employee_no_snapshot',
        ),
        migrations.RemoveField(
            model_name='agentdispatchdecision',
            name='recommended_contact_name_snapshot',
        ),
        migrations.RemoveField(
            model_name='assignmentattempt',
            name='assigned_to_sub_at',
        ),
        migrations.RemoveField(
            model_name='assignmentattempt',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='assignmentattempt',
            name='contact_employee_no_snapshot',
        ),
        migrations.RemoveField(
            model_name='assignmentattempt',
            name='contact_name_snapshot',
        ),
        migrations.RemoveField(
            model_name='assignmentattempt',
            name='department',
        ),
        migrations.RemoveField(
            model_name='assignmentattempt',
            name='department_name_snapshot',
        ),
        migrations.RemoveField(
            model_name='assignmentattempt',
            name='sub_contact',
        ),
        migrations.RemoveField(
            model_name='assignmentattempt',
            name='sub_contact_employee_no_snapshot',
        ),
        migrations.RemoveField(
            model_name='assignmentattempt',
            name='sub_contact_name_snapshot',
        ),
        migrations.RemoveField(
            model_name='assignmentattempt',
            name='sub_department',
        ),
        migrations.RemoveField(
            model_name='assignmentattempt',
            name='sub_department_name_snapshot',
        ),
        migrations.RemoveField(
            model_name='assignmentattempt',
            name='welink_message_id',
        ),
        migrations.RemoveField(
            model_name='processingrunscopeitem',
            name='prepared_contact',
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='current_department',
            field=models.ForeignKey(help_text='当前接收部门，可在有效转派时变更', on_delete=django.db.models.deletion.PROTECT, related_name='current_assignment_attempts', to='core.department'),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='current_department_name_snapshot',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='feedback_reason_code',
            field=models.CharField(blank=True, choices=[('major_background_mismatch', '专业背景不匹配'), ('research_experience_mismatch', '科研经历不符合'), ('key_capability_mismatch', '关键能力不匹配'), ('project_internship_mismatch', '项目/实习经历不匹配'), ('position_direction_mismatch', '岗位方向不匹配'), ('other', '其他')], db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='feedback_reason_label_snapshot',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='initial_department',
            field=models.ForeignKey(help_text='首次分配的二级部门，创建后不可变更', on_delete=django.db.models.deletion.PROTECT, related_name='initial_assignment_attempts', to='core.department'),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='initial_department_name_snapshot',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='assignmentattempt',
            name='status',
            field=models.CharField(choices=[('pending_dispatch', '待下发'), ('pending_review', '待 HR 复核'), ('dispatched', '已下发部门'), ('passed', '已通过'), ('rejected', '未通过'), ('cancelled', '已取消')], default='pending_dispatch', max_length=32),
        ),
        migrations.AlterField(
            model_name='candidateworkflow',
            name='block_reason',
            field=models.CharField(blank=True, choices=[('job_hc_exhausted', '当前任务岗位 HC 容量已用尽')], max_length=64),
        ),
        migrations.AddIndex(
            model_name='assignmentattempt',
            index=models.Index(fields=['current_department', 'status'], name='core_assign_current_b5d509_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentattempt',
            index=models.Index(fields=['initial_department', 'status'], name='core_assign_initial_11df5c_idx'),
        ),
        migrations.DeleteModel(
            name='AssignmentHandoff',
        ),
        migrations.AddField(
            model_name='assignmenthandlingevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_handling_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmenthandlingevent',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handling_events', to='core.assignmentattempt'),
        ),
        migrations.AddField(
            model_name='assignmenthandlingevent',
            name='from_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_events_from', to='core.department'),
        ),
        migrations.AddField(
            model_name='assignmenthandlingevent',
            name='to_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_events_to', to='core.department'),
        ),
        migrations.AddIndex(
            model_name='assignmenthandlingevent',
            index=models.Index(fields=['attempt', 'occurred_at'], name='core_assign_attempt_23c400_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmenthandlingevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='core_assign_event_t_bf5e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmenthandlingevent',
            index=models.Index(fields=['to_department', 'occurred_at'], name='core_assign_to_depa_b08b9e_idx'),
        ),
    ]
