# Generated by Django 4.2.16 on 2026-08-24 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_department_inbox_breaking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmenthandlingevent',
            name='from_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_events_from', to='core.department'),
        ),
        migrations.AlterField(
            model_name='assignmenthandlingevent',
            name='to_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_events_to', to='core.department'),
        ),
    ]
