# Generated by Django 4.2.16 on 2026-08-25 01:19

from django.db import migrations, models


def normalize_jobs_and_seed_candidate_tags(apps, schema_editor):
    Job = apps.get_model("core", "Job")
    Candidate = apps.get_model("core", "Candidate")

    for job in Job.objects.select_related("department__parent"):
        department = job.department
        if department and department.level == 3:
            parent = department.parent
            if parent and parent.level == 2:
                job.department_id = parent.id
                job.save(update_fields=["department"])
                continue
        if not department or department.level != 2:
            job.department_id = None
            job.is_active = False
            job.save(update_fields=["department", "is_active"])

    for candidate in Candidate.objects.all().iterator():
        tag_ids = {
            tag_id
            for tag_id in (
                candidate.first_degree_tag_id,
                candidate.highest_degree_tag_id,
            )
            if tag_id
        }
        candidate.school_tags.set(tag_ids)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_protect_department_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='school_tags',
            field=models.ManyToManyField(blank=True, help_text='当前有效简历全部教育经历映射出的去重院校标签', related_name='candidates', to='core.schooltag'),
        ),
        migrations.RunPython(
            normalize_jobs_and_seed_candidate_tags,
            migrations.RunPython.noop,
        ),
    ]
