# Generated by Django 4.2.16 on 2026-06-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('hr', 'HR'), ('secondary_contact', '二级接口人'), ('tertiary_contact', '三级接口人'), ('admin', '管理员')], default='hr', max_length=32),
        ),
    ]
